### ISSUE TITLE
Golden reference from ISS and compiled do not match

### ISSUE THREAD

**Issue by marcospazianibrunella** [marcospazianibrunella/SweRV-LC#13]
I’ve made the first version of a self-checking test bench with the golden reference you’ve provided.

It stops at instruction #5 with the following error:

> [          1] Received instruction: 595552b7 -- Expected Instruction: 595552b7
> [          2] Received instruction: 5552829b -- Expected Instruction: 5552829b
> [          3] Received instruction: 7c029073 -- Expected Instruction: 7c029073
> [          4] Received instruction: 00018117 -- Expected Instruction: 00018117
> [          5] Received instruction: 65410113 -- Expected Instruction: 66410113

The instruction is an `addi` on both sides, but the immediate on the golden reference is 0x664, while my compiled code is 0x654.

Now I'm launching the ISS to generate a consistent gold reference. Is this sufficient to launch the ISS?
```bash
$ SweRV-ISS/build-Linux/whisper --newlib SweRV-golden/cmark.exe --xlen 64
```

**Comment by irfanwaheed** [comment]
Our local repo for whisper is slightly modified from the open-source one, but the following instructions should still be useful. You need to have to the  C++ Boost Library installed on your system. We build whisper like this:
make BOOST_ROOT=/projects/shared/boost_1_77_0

You must have the RISCV toolchain in your path. Then you can run whisper like this:
build-Linux/whisper  --config configs/whisper.json    elf_file -f out/output.log --isa imcfdv --xlen=64

The configs/whisper.json file can be picked from the SweRV RTL directory under snapshots/default.
elf_file is the elf file you want to simulate
The output file is out/output.log

**Comment by marcospazianibrunella** [comment]
I get the following error when trying to run the command above:

> A CSR number must be provided in configuration of non-standard CSR mhpmcounter3h
A CSR number must be provided in configuration of non-standard CSR mhpmcounter4h
A CSR number must be provided in configuration of non-standard CSR mhpmcounter5h
A CSR number must be provided in configuration of non-standard CSR mhpmcounter6h

**Comment by irfanwaheed** [comment]
i have emailed you a json file
