### ISSUE TITLE
64-bit DIV producing incorrect result

### ISSUE THREAD

**Issue by irfanwaheed** [marcospazianibrunella/SweRV-LC#5]
The following test should produce result 0x29A, but its producing 0x0

    **_li x29, 0x7d0
    li x30, 0x3
    divu x31,x29,x30_**

**Comment by marcospazianibrunella** [comment]
I'm isolating the divider to spot the issue

**Comment by marcospazianibrunella** [comment]
I've included the original 32-bit divider, and the result is consistent between the two. I have set up a testbench for it. Can you please check?

**Comment by marcospazianibrunella** [comment]
The latest commit should fix the issue. I've included the waveform file. Latency is increased for the divider.

**Comment by irfanwaheed** [comment]
I am getting Xs from the divider because of this: 
assign shortq_shift_ff[5:0]    = ({6{shortq_shift_xx[3]}} & 6'b01_1111) |   // 31
                                 ({6{shortq_shift_xx[2]}} & 6'b01_1000) |   // 24
                                 ({6{shortq_shift_xx[1]}} & 6'b01_0000) |   // 16
                                 ({6{shortq_shift_xx[0]}} & 6'b00_1000);    //  8

shortq_shift_ff is defined as 8 bits but you are only assigning 6 bits.

**Comment by irfanwaheed** [comment]
Changing it to this fixes it but please review if this is correct:
   assign shortq_shift_ff[7:0]    = ({6{shortq_shift_xx[3]}} & 8'b0001_1111) |   // 31
                                    ({6{shortq_shift_xx[2]}} & 8'b0001_1000) |   // 24
                                    ({6{shortq_shift_xx[1]}} & 8'b0001_0000) |   // 16
                                    ({6{shortq_shift_xx[0]}} & 8'b0000_1000);    //  8

**Comment by marcospazianibrunella** [comment]
I'm getting three different results! On Verilator, it worked also before (screenshot attached). In Vivado, it never worked (screenshot attached). I'm sticking with Verilator for further tests, but I'll not be able to catch X's.

![Verilator](https://user-images.githubusercontent.com/6264198/146346967-c6f69c7d-6928-4d71-9adb-011601953e67.png)

![Vivado](https://user-images.githubusercontent.com/6264198/146346974-a3c5428f-2d4b-45a2-9718-aee0d6cdf2b6.png)
