### ISSUE TITLE
DCCM addressing structure issues

### ISSUE THREAD

**Issue by irfanwaheed** [marcospazianibrunella/SweRV-LC#6]
The new DCCM (without ECC) is **2048x64**. The original was **2048x32.**
This is twice the size (**64kB --> 128kB**)
This implies the following  **(please confirm)**: 

RV_DCCM_BITS should be 17
RV_DCCM_WIDTH_BITS should be 3
RV_LSU_SB_BITS should be 17

In lsu_dccm_mem, I also changed the following lines **(please confirm)**: 
  logic [DCCM_NUM_BANKS-1:0] [DCCM_BITS-1:(DCCM_BANK_BITS+**3**)]   addr_bank;
  logic [DCCM_NUM_BANKS-1:0] [DCCM_BITS-1:(DCCM_BANK_BITS+**3**)]   addr_bank_q;

      assign  wren_bank[i]        = dccm_wren & (dccm_wr_addr[3+:DCCM_BANK_BITS] == i);
      assign  rden_bank[i]        = dccm_rden & ((dccm_rd_addr_hi[3+:DCCM_BANK_BITS] == i) | (dccm_rd_addr_lo[2+:DCCM_BANK_BITS] == i));

**Comment by marcospazianibrunella** [comment]
Fixed by latest commit
